### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by OracleToes** [0xbitches/ComfyUI-LCM#2]
I cloned the repo into my custom nodes folder and restarted comfyUI, placed the sampler node and connected it to a preview node an when i execute, i get the following error: 
```Error occurred when executing LCMSampler:

[Errno 2] No such file or directory: '/home/momiro/.cache/huggingface/hub/models--SimianLuo--LCM_Dreamshaper_v7/refs/main'

  File "/home/momiro/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/momiro/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/momiro/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/momiro/AI/ComfyUI/custom_nodes/ComfyUI-LCM/nodes.py", line 46, in sample
    self.pipe = LatentConsistencyModelPipeline.from_pretrained(
  File "/home/momiro/AI/ComfyUI/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 939, in from_pretrained
    cached_folder = cls.download(
  File "/home/momiro/AI/ComfyUI/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1599, in download
    cached_folder = snapshot_download(
  File "/home/momiro/AI/ComfyUI/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/momiro/AI/ComfyUI/venv/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
    with open(ref_path) as f:
```

I looked in that folder where it's looking for the file, but i have two .txt files there and nothing else, someone on reddit suggested deleting the "hub" folder and restarting, but that didn't work for me.
Are we supposed to download the model from huggingface and place it in that folder? if so that should be in the installation instructions, but I don't exactly see how the file structure matches up. Any help? this looks really interesting.

**Comment by lienminhquang** [comment]
I have the same issue too. Idk why, but he force the Diffuser lib to load model from local file only. You can do a workaround by comment this line and restart your ComfyUI server. https://github.com/0xbitches/ComfyUI-LCM/blob/22a85cbeb8d57e8c98894e95c55bca31d5d9e1c7/nodes.py#L48C39-L48C39
It works for me.

@0xbitches is it intented?

**Comment by iterhating** [comment]
I am not saying this is the right way. I'm sure things will be fixed to be smoother and the model installation homogenized with the standard practice.
That being said, I had the same error as you and finally have it working.

0. Delete everything you downloaded from ComfyUI-LCM, and whatever folders you made
1. Update Comfyui
2. clone comfyui-lcm into /custom_nodes
3. Do not start comfyui!
4. Instead go to cmd/powershell/terminal and activate your comfyui environment
5. Check what version of diffusers you have, must be >= 0.21.4, update if needed
6. Inside that same environment, open/start python
7. run these commands:
```
from diffusers import StableDiffusionPipeline

repo_id = "SimianLuo/LCM_Dreamshaper_v7"
pipe = StableDiffusionPipeline.from_pretrained(repo_id, use_safetensors=True)

```
8. This will make the folders you were struggling with, I guess it's like git clone, but for huggingface.
9. Delete file: C:\Users\YourUserName\.cache\huggingface\hub\models--SimianLuo--LCM_Dreamshaper_v7\snapshots\c7f9b672c65a664af57d1de926819fd79cb26eb8\tokenizer\added_tokens.json
10. open in editor \custom_nodes\ComfyUI-LCM\nodes.py and below line 49 line add "safety_checker=None"
```
self.pipe = LatentConsistencyModelPipeline.from_pretrained(
    model, // Ignore, just a path to my local model folder
    local_files_only=True,
    scheduler=self.scheduler,
    safety_checker=None, // This is the line you need to add
)
```
11. Save and close. Close all terminals. Start ComfyUI. Things will download. Try a generation.


So anyway, this will probably be obsolete soon, and might be incorrect now, but it's my best reconstruction of what I did to get it working. Good luck. It apparently is possible!

**Comment by iterhating** [comment]
> I have the same issue too. Idk why, but he force the Diffuser lib to load model from local file only. You can do a workaround by comment this line. https://github.com/0xbitches/ComfyUI-LCM/blob/22a85cbeb8d57e8c98894e95c55bca31d5d9e1c7/nodes.py#L48C39-L48C39 It works for me.

Hahahaha, Is that seriously a working workaround? I fiddled with the line before it to no avail.

**Comment by lienminhquang** [comment]
> > I have the same issue too. Idk why, but he force the Diffuser lib to load model from local file only. You can do a workaround by comment this line. https://github.com/0xbitches/ComfyUI-LCM/blob/22a85cbeb8d57e8c98894e95c55bca31d5d9e1c7/nodes.py#L48C39-L48C39 It works for me.
> 
> Hahahaha, Is that seriously a working workaround? I fiddled with the line before it to no avail.

Did you restart your ComfyUI server after comment it?

**Comment by iterhating** [comment]
> > > I have the same issue too. Idk why, but he force the Diffuser lib to load model from local file only. You can do a workaround by comment this line. https://github.com/0xbitches/ComfyUI-LCM/blob/22a85cbeb8d57e8c98894e95c55bca31d5d9e1c7/nodes.py#L48C39-L48C39 It works for me.
> > 
> > 
> > Hahahaha, Is that seriously a working workaround? I fiddled with the line before it to no avail.
> 
> Did you restart your ComfyUI server?

Literally 8 times trying different things before I got on the track that worked. But I didn't comment that line, I was trying to point the local folder path in the correct direction--which might have worked if I was more familiar with the hugging/diffusors architecture and included the other files (maybe, it was complaining about the path right away).

**Comment by lienminhquang** [comment]
> > > > I have the same issue too. Idk why, but he force the Diffuser lib to load model from local file only. You can do a workaround by comment this line. https://github.com/0xbitches/ComfyUI-LCM/blob/22a85cbeb8d57e8c98894e95c55bca31d5d9e1c7/nodes.py#L48C39-L48C39 It works for me.
> > > 
> > > 
> > > Hahahaha, Is that seriously a working workaround? I fiddled with the line before it to no avail.
> > 
> > 
> > Did you restart your ComfyUI server?
> 
> Literally 8 times trying different things before I got on the track that worked.

It worked for me at the first try.

**Comment by iterhating** [comment]
> > > > > I have the same issue too. Idk why, but he force the Diffuser lib to load model from local file only. You can do a workaround by comment this line. https://github.com/0xbitches/ComfyUI-LCM/blob/22a85cbeb8d57e8c98894e95c55bca31d5d9e1c7/nodes.py#L48C39-L48C39 It works for me.
> > > > 
> > > > 
> > > > Hahahaha, Is that seriously a working workaround? I fiddled with the line before it to no avail.
> > > 
> > > 
> > > Did you restart your ComfyUI server?
> > 
> > 
> > Literally 8 times trying different things before I got on the track that worked.
> 
> It worked for me at the first try.

That was not my experience (in general. perhaps commenting that line works, if so, likely does work first time after rebooting the server).

**Comment by OracleToes** [comment]
So i might have found a fix for me that works, i was digging around in my venv and i saw a line about offline files only, and in the nodes.py of this repo on line 48 i changed the `local_files_only=True,` to `False` and it started downloading the repository from huggingface for me. I am unable to confirm if this works yet because it's still downloading the model.

**Comment by 0xbitches** [comment]
`local_files_only=True` is not intended at all. It was from the forked repo and I apologize for not having looked at it better. 

Closing this for now as the latest commit should fix it.

**Comment by thenickdude** [comment]
Removing `local_files_only=True` is a double-edged sword, because it causes the LCM Sampler to hang forever if no network is available (even if the model is cached locally, it wants to send a request to check if there is a new version available).
