### ISSUE TITLE
Accept conditioning input

### ISSUE THREAD

**Issue by seanphan** [0xbitches/ComfyUI-LCM#3]
Hi,

Thank you for making LCM as custom node super fast. Can't wait to try.

By the way I don't see the conditioning input. Is it because the LCM doesn't work with conditioning (e.g: controlnet, Lora, etc) or this is yet supported via your node? For the latter, do you have plan to work on it?

Bests,

Sean

**Comment by 0xbitches** [comment]
Yes, since LCMs are a different class of model, it currently does not support LoRA, ControlNet, etc unfortunately. 

While I do hope to see these implemented someday, I simply donot have the time to go through each of them.
