### ISSUE TITLE
Please, replace size with width and height

### ISSUE THREAD

**Issue by GaidamakUA** [0xbitches/ComfyUI-LCM#5]
This model is similar to SD that it likes to crop heads when image is square. So I like to make images 512 by 768.
This is 3 line fix, so I see no reason to make pull request. Thank you in advance.

**Comment by jFkd1** [comment]
Looks like the `LCM_img2img_Sampler` already implements that, the dev probably forgot to change the base Sampler.

**Comment by 0xbitches** [comment]
Fixed in https://github.com/0xbitches/ComfyUI-LCM/commit/697ec09ab524be4733d851eb0f470be107629fb6
